variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprintegrationfunction'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprintegrationfunctionrepository'
  serviceName: 'PRDRWDWEBFA1412'