variables:
- group: ServiceConnections
- name: azureSubscription
  value: $(ServiceConnectionPRD1)
- name: docker.imageName
  value: 'eprintegrationfunction'
- name: acr.azureContainerRegistryName
  value: 'prdrwdinfac1401'
- name: acr.repositoryName
  value: 'eprintegrationfunctionrepository'
- name: serviceName
  value: 'PRDRWDWEBFA1412'